// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SenacQuizApp.Data;

#nullable disable

namespace SenacQuizApp.Migrations
{
    [DbContext(typeof(QuizAppContexto))]
    [Migration("20260819025831_ModificaTabelaAlternativas")]
    partial class ModificaTabelaAlternativas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SenacQuizApp.Enums.PerguntaTema", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("PerguntaTemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Hardware"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Programação"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Redes"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Segurança Digital"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Sistemas Operacionais"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Ferramentas de Produtividade"
                        });
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Conquista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Conquistas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Pergunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TemaId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TemaId");

                    b.ToTable("Perguntas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.PerguntaAlternativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorreta")
                        .HasColumnType("boolean");

                    b.Property<int>("PerguntaId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PerguntaId");

                    b.ToTable("PerguntasAlternativas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.PerguntaRespondida", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("PerguntaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Acertou")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DataDeResposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("PontuacaoFinal")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "PerguntaId");

                    b.HasIndex("PerguntaId");

                    b.ToTable("PerguntasRespondidas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcertosConsecutivos")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataDeCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataDeNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxAcertosConsecutivos")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<int>("PontuacaoTotal")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalAcertos")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRespondidos")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.UsuarioConquista", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("ConquistaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataDeAquisicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "ConquistaId");

                    b.HasIndex("ConquistaId");

                    b.ToTable("UsuarioConquistas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Pergunta", b =>
                {
                    b.HasOne("SenacQuizApp.Enums.PerguntaTema", "Tema")
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.PerguntaAlternativa", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Pergunta", "Pergunta")
                        .WithMany("Alternativas")
                        .HasForeignKey("PerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pergunta");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.PerguntaRespondida", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Pergunta", "Pergunta")
                        .WithMany("PerguntasRespondidas")
                        .HasForeignKey("PerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.Usuario", "Usuario")
                        .WithMany("PerguntasRespondidas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pergunta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.UsuarioConquista", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Conquista", "Conquista")
                        .WithMany("UsuarioConquistas")
                        .HasForeignKey("ConquistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.Usuario", "Usuario")
                        .WithMany("UsuarioConquistas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conquista");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Conquista", b =>
                {
                    b.Navigation("UsuarioConquistas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Pergunta", b =>
                {
                    b.Navigation("Alternativas");

                    b.Navigation("PerguntasRespondidas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuario", b =>
                {
                    b.Navigation("PerguntasRespondidas");

                    b.Navigation("UsuarioConquistas");
                });
#pragma warning restore 612, 618
        }
    }
}
