// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SenacQuizApp.Data;

#nullable disable

namespace SenacQuizApp.Migrations
{
    [DbContext(typeof(QuizAppContexto))]
    [Migration("20260829032142_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuestaoQuizDiario", b =>
                {
                    b.Property<int>("QuestoesId")
                        .HasColumnType("integer");

                    b.Property<int>("QuizzesId")
                        .HasColumnType("integer");

                    b.HasKey("QuestoesId", "QuizzesId");

                    b.HasIndex("QuizzesId");

                    b.ToTable("QuizQuestoes", (string)null);
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Conquista", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Meta")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("TemaId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TemaId");

                    b.ToTable("Conquistas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Questoes.Alternativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EhCorreta")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoId");

                    b.ToTable("Alternativas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Questoes.Questao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<int>("NivelId")
                        .HasColumnType("integer");

                    b.Property<int>("TemaId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoId")
                        .HasColumnType("integer");

                    b.Property<bool?>("VerdadeiroFalso")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NivelId");

                    b.HasIndex("TemaId");

                    b.HasIndex("TipoId");

                    b.ToTable("Questoes");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Questoes.QuestaoNivel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Valor")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("QuestaoNiveis");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Questoes.QuestaoTema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("QuestaoTemas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Questoes.QuestaoTipo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("QuestaoTipos");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.QuizDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Concluido")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("DataConcluido")
                        .HasColumnType("timestamptz");

                    b.Property<DateOnly>("DataExibido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<DateTimeOffset>("DataIniciado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PontuacaoTotal")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("TempoDeConclusao")
                        .HasColumnType("interval");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "DataExibido")
                        .IsUnique();

                    b.ToTable("QuizzesDiarios");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.QuizRush", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DataFinalizado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DataIniciado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PontuacaoTotal")
                        .HasColumnType("integer");

                    b.Property<int>("Streak")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Tempo")
                        .HasColumnType("interval");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("QuizzesRush");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DataDeCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("DataDeNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuarios.UsuarioAcesso", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DataAcesso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.HasKey("UsuarioId", "DataAcesso");

                    b.ToTable("Acessos");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuarios.UsuarioConquista", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("ConquistaId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DataDeAquisicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UsuarioId", "ConquistaId");

                    b.HasIndex("ConquistaId");

                    b.ToTable("UsuarioConquistas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuarios.UsuarioNivel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PontosMax")
                        .HasColumnType("integer");

                    b.Property<int>("PontosMin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UsuarioNiveis");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuarios.UsuarioResposta", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("integer");

                    b.Property<bool>("Acertou")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("DataDeResposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PontuacaoFinal")
                        .HasColumnType("integer");

                    b.Property<int>("QuestaoValor")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "QuizId", "QuestaoId");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("QuizId");

                    b.ToTable("UsuarioRespostas", (string)null);
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuarios.UsuarioStats", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("AtualAcertosSeguidos")
                        .HasColumnType("integer");

                    b.Property<int>("MaxAcertosSeguidos")
                        .HasColumnType("integer");

                    b.Property<int>("NivelId")
                        .HasColumnType("integer");

                    b.Property<int>("PontuacaoTotal")
                        .HasColumnType("integer");

                    b.Property<int>("TotalAcertos")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRespondidos")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId");

                    b.HasIndex("NivelId");

                    b.ToTable("UsuarioStats");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuarios.UsuarioTemasProgresso", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("TemaId")
                        .HasColumnType("integer");

                    b.Property<int>("RespostasCorretas")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "TemaId");

                    b.HasIndex("TemaId");

                    b.ToTable("UsuarioTemasProgressos");
                });

            modelBuilder.Entity("QuestaoQuizDiario", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Questoes.Questao", null)
                        .WithMany()
                        .HasForeignKey("QuestoesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.QuizDiario", null)
                        .WithMany()
                        .HasForeignKey("QuizzesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Conquista", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Questoes.QuestaoTema", "Tema")
                        .WithMany()
                        .HasForeignKey("TemaId");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Questoes.Alternativa", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Questoes.Questao", "Questao")
                        .WithMany("Alternativas")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Questoes.Questao", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Questoes.QuestaoNivel", "Nivel")
                        .WithMany("Questoes")
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.Questoes.QuestaoTema", "Tema")
                        .WithMany("Questoes")
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.Questoes.QuestaoTipo", "Tipo")
                        .WithMany("Questoes")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nivel");

                    b.Navigation("Tema");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.QuizDiario", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.QuizRush", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuarios.UsuarioAcesso", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Usuarios.Usuario", "Usuario")
                        .WithMany("Acessos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuarios.UsuarioConquista", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Conquista", "Conquista")
                        .WithMany("UsuarioConquistas")
                        .HasForeignKey("ConquistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.Usuarios.Usuario", "Usuario")
                        .WithMany("Conquistas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conquista");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuarios.UsuarioResposta", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Questoes.Questao", "Questao")
                        .WithMany("UsuarioRespostas")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.QuizDiario", "Quiz")
                        .WithMany("UsuarioRespostas")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.Usuarios.Usuario", "Usuario")
                        .WithMany("Respostas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");

                    b.Navigation("Quiz");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuarios.UsuarioStats", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Usuarios.UsuarioNivel", "Nivel")
                        .WithMany()
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.Usuarios.Usuario", "Usuario")
                        .WithOne("Stats")
                        .HasForeignKey("SenacQuizApp.Modelos.Usuarios.UsuarioStats", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nivel");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuarios.UsuarioTemasProgresso", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Questoes.QuestaoTema", "Tema")
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tema");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Conquista", b =>
                {
                    b.Navigation("UsuarioConquistas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Questoes.Questao", b =>
                {
                    b.Navigation("Alternativas");

                    b.Navigation("UsuarioRespostas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Questoes.QuestaoNivel", b =>
                {
                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Questoes.QuestaoTema", b =>
                {
                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Questoes.QuestaoTipo", b =>
                {
                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.QuizDiario", b =>
                {
                    b.Navigation("UsuarioRespostas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuarios.Usuario", b =>
                {
                    b.Navigation("Acessos");

                    b.Navigation("Conquistas");

                    b.Navigation("Respostas");

                    b.Navigation("Stats")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
