// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SenacQuizApp.Data;

#nullable disable

namespace SenacQuizApp.Migrations
{
    [DbContext(typeof(QuizAppContexto))]
    [Migration("20260818043439_AtualizaPerguntas")]
    partial class AtualizaPerguntas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SenacQuizApp.Entidades.Alternativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EhCorreta")
                        .HasColumnType("boolean");

                    b.Property<int>("PerguntaId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PerguntaId");

                    b.ToTable("Alternativas");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Conquista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Conquistas");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.NivelUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PontosMax")
                        .HasColumnType("integer");

                    b.Property<int>("PontosMin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("NiveisUsuarios");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Pergunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TemaId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TemaId");

                    b.ToTable("Perguntas");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.PerguntaRespondida", b =>
                {
                    b.Property<int>("QuizTentativaId")
                        .HasColumnType("integer");

                    b.Property<int>("PerguntaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Acertou")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DataDeResposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("PontuacaoFinal")
                        .HasColumnType("integer");

                    b.Property<int>("QuizTentativaQuizId")
                        .HasColumnType("integer");

                    b.Property<int>("QuizTentativaUsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("QuizTentativaId", "PerguntaId");

                    b.HasIndex("PerguntaId");

                    b.HasIndex("QuizTentativaUsuarioId", "QuizTentativaQuizId");

                    b.ToTable("PerguntasRespondidas");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataDeCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataExibicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuantidadePerguntas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.HasKey("Id");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.QuizHistorico", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.Property<bool>("Concluido")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int?>("PontuacaoFinal")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "QuizId");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizzesHistorico");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.QuizPergunta", b =>
                {
                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.Property<int>("PerguntaId")
                        .HasColumnType("integer");

                    b.HasKey("QuizId", "PerguntaId");

                    b.HasIndex("PerguntaId");

                    b.ToTable("QuizzesPerguntas");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcertosConsecutivos")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataDeCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataDeNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxAcertosConsecutivos")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NivelUsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PontuacaoTotal")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalAcertos")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRespondidos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NivelUsuarioId");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.UsuarioConquista", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("ConquistaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataDeAquisicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "ConquistaId");

                    b.HasIndex("ConquistaId");

                    b.ToTable("UsuarioConquistas");
                });

            modelBuilder.Entity("SenacQuizApp.Enums.PerguntaTema", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("PerguntaTemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Hardware"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Programação"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Redes"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Segurança Digital"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Sistemas Operacionais"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Ferramentas de Produtividade"
                        });
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Alternativa", b =>
                {
                    b.HasOne("SenacQuizApp.Entidades.Pergunta", "Pergunta")
                        .WithMany("Alternativas")
                        .HasForeignKey("PerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pergunta");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Pergunta", b =>
                {
                    b.HasOne("SenacQuizApp.Enums.PerguntaTema", "Tema")
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.PerguntaRespondida", b =>
                {
                    b.HasOne("SenacQuizApp.Entidades.Pergunta", "Pergunta")
                        .WithMany("PerguntasRespondidas")
                        .HasForeignKey("PerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Entidades.QuizHistorico", "QuizTentativa")
                        .WithMany("PerguntasRespondidas")
                        .HasForeignKey("QuizTentativaUsuarioId", "QuizTentativaQuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pergunta");

                    b.Navigation("QuizTentativa");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.QuizHistorico", b =>
                {
                    b.HasOne("SenacQuizApp.Entidades.Quiz", "Quiz")
                        .WithMany("QuizTentativas")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Entidades.Usuario", "Usuario")
                        .WithMany("QuizTentativas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.QuizPergunta", b =>
                {
                    b.HasOne("SenacQuizApp.Entidades.Pergunta", "Pergunta")
                        .WithMany("QuizPerguntas")
                        .HasForeignKey("PerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Entidades.Quiz", "Quiz")
                        .WithMany("QuizPerguntas")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pergunta");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Usuario", b =>
                {
                    b.HasOne("SenacQuizApp.Entidades.NivelUsuario", "Nivel")
                        .WithMany()
                        .HasForeignKey("NivelUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.UsuarioConquista", b =>
                {
                    b.HasOne("SenacQuizApp.Entidades.Conquista", "Conquista")
                        .WithMany("UsuarioConquistas")
                        .HasForeignKey("ConquistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Entidades.Usuario", "Usuario")
                        .WithMany("UsuarioConquistas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conquista");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Conquista", b =>
                {
                    b.Navigation("UsuarioConquistas");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Pergunta", b =>
                {
                    b.Navigation("Alternativas");

                    b.Navigation("PerguntasRespondidas");

                    b.Navigation("QuizPerguntas");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Quiz", b =>
                {
                    b.Navigation("QuizPerguntas");

                    b.Navigation("QuizTentativas");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.QuizHistorico", b =>
                {
                    b.Navigation("PerguntasRespondidas");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Usuario", b =>
                {
                    b.Navigation("QuizTentativas");

                    b.Navigation("UsuarioConquistas");
                });
#pragma warning restore 612, 618
        }
    }
}
