// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SenacQuizApp.banco.config;

#nullable disable

namespace SenacQuizApp.Migrations
{
    [DbContext(typeof(AppContexto))]
    [Migration("20260814031958_AdicionaTabelaPerguntasRespondidas")]
    partial class AdicionaTabelaPerguntasRespondidas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SenacQuizApp.Entidades.Conquista", b =>
                {
                    b.Property<int>("ConquistaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConquistaId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("ConquistaId");

                    b.ToTable("Conquistas");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.NivelPergunta", b =>
                {
                    b.Property<int>("NivelPerguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NivelPerguntaId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer");

                    b.HasKey("NivelPerguntaId");

                    b.ToTable("NivelPergunta");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.NivelUsuario", b =>
                {
                    b.Property<int>("NivelUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NivelUsuarioId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PontosMax")
                        .HasColumnType("integer");

                    b.Property<int>("PontosMin")
                        .HasColumnType("integer");

                    b.HasKey("NivelUsuarioId");

                    b.ToTable("NivelUsuario");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Pergunta", b =>
                {
                    b.Property<int>("PerguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PerguntaId"));

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NivelPerguntaId")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("Respostas")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("TemaPerguntaId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PerguntaId");

                    b.HasIndex("NivelPerguntaId");

                    b.HasIndex("TemaPerguntaId");

                    b.ToTable("Perguntas");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.PerguntaRespondida", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("PerguntaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Acertou")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataDeResposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PerguntaRespondidaId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "PerguntaId");

                    b.HasIndex("PerguntaId");

                    b.ToTable("PerguntasRespondidas");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.TemaPergunta", b =>
                {
                    b.Property<int>("TemaPerguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TemaPerguntaId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("TemaPerguntaId");

                    b.ToTable("TemaPergunta");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxAcertosConsecutivos")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("NivelUsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("PontuacaoTotal")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalAcertos")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRespondidos")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.HasIndex("NivelUsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.UsuarioConquista", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("ConquistaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataDeAquisicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UsuarioConquistaId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "ConquistaId");

                    b.HasIndex("ConquistaId");

                    b.ToTable("UsuarioConquistas");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Pergunta", b =>
                {
                    b.HasOne("SenacQuizApp.Entidades.NivelPergunta", "Nivel")
                        .WithMany()
                        .HasForeignKey("NivelPerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Entidades.TemaPergunta", "Tema")
                        .WithMany()
                        .HasForeignKey("TemaPerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nivel");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.PerguntaRespondida", b =>
                {
                    b.HasOne("SenacQuizApp.Entidades.Pergunta", "Pergunta")
                        .WithMany("PerguntasRespondidas")
                        .HasForeignKey("PerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Entidades.Usuario", "Usuario")
                        .WithMany("PerguntasRespondidas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pergunta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Usuario", b =>
                {
                    b.HasOne("SenacQuizApp.Entidades.NivelUsuario", "Nivel")
                        .WithMany()
                        .HasForeignKey("NivelUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.UsuarioConquista", b =>
                {
                    b.HasOne("SenacQuizApp.Entidades.Conquista", "Conquista")
                        .WithMany("UsuarioConquistas")
                        .HasForeignKey("ConquistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Entidades.Usuario", "Usuario")
                        .WithMany("UsuarioConquistas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conquista");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Conquista", b =>
                {
                    b.Navigation("UsuarioConquistas");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Pergunta", b =>
                {
                    b.Navigation("PerguntasRespondidas");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Usuario", b =>
                {
                    b.Navigation("PerguntasRespondidas");

                    b.Navigation("UsuarioConquistas");
                });
#pragma warning restore 612, 618
        }
    }
}
