// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SenacQuizApp.Data;

#nullable disable

namespace SenacQuizApp.Migrations
{
    [DbContext(typeof(QuizAppContexto))]
    [Migration("20260824170211_AtualizaRespostas")]
    partial class AtualizaRespostas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuestaoQuiz", b =>
                {
                    b.Property<int>("QuestoesId")
                        .HasColumnType("integer");

                    b.Property<int>("QuizzesId")
                        .HasColumnType("integer");

                    b.HasKey("QuestoesId", "QuizzesId");

                    b.HasIndex("QuizzesId");

                    b.ToTable("QuizQuestoes", (string)null);
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Alternativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorreta")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoId");

                    b.ToTable("Alternativas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Conquista", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Conquistas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Questao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<int>("NivelId")
                        .HasColumnType("integer");

                    b.Property<int>("TemaId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoId")
                        .HasColumnType("integer");

                    b.Property<bool?>("Verdadeira")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NivelId");

                    b.HasIndex("TemaId");

                    b.HasIndex("TipoId");

                    b.ToTable("Questoes");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.QuestaoNivel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("QuestaoNiveis");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.QuestaoTema", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("QuestaoTemas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.QuestaoTipo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("QuestaoTipos");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataConcluido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataExibido")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsConcluido")
                        .HasColumnType("boolean");

                    b.Property<int>("PontuacaoTotal")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("TempoDeConclusao")
                        .HasColumnType("interval");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "DataExibido")
                        .IsUnique();

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataDeCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataDeNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.UsuarioConquista", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("ConquistaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataDeAquisicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UsuarioId", "ConquistaId");

                    b.HasIndex("ConquistaId");

                    b.ToTable("UsuarioConquistas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.UsuarioNivel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UsuarioNiveis");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.UsuarioResposta", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("integer");

                    b.Property<bool>("Acertou")
                        .HasColumnType("boolean");

                    b.Property<int>("Bonus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataDeResposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("PontuacaoFinal")
                        .HasColumnType("integer");

                    b.Property<int>("PontuacaoInicial")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "QuizId", "QuestaoId");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("QuizId");

                    b.ToTable("UsuarioRespostas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.UsuarioStats", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("AtualAcertosConsecutivos")
                        .HasColumnType("integer");

                    b.Property<int>("MaxAcertosConsecutivos")
                        .HasColumnType("integer");

                    b.Property<int>("NivelId")
                        .HasColumnType("integer");

                    b.Property<int>("PontuacaoTotal")
                        .HasColumnType("integer");

                    b.Property<int>("TotalAcertos")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRespondidos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NivelId");

                    b.ToTable("UsuarioStats");
                });

            modelBuilder.Entity("QuestaoQuiz", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Questao", null)
                        .WithMany()
                        .HasForeignKey("QuestoesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.Quiz", null)
                        .WithMany()
                        .HasForeignKey("QuizzesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Alternativa", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Questao", "Questao")
                        .WithMany("Alternativas")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Questao", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.QuestaoNivel", "Nivel")
                        .WithMany("Questoes")
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.QuestaoTema", "Tema")
                        .WithMany("Questoes")
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.QuestaoTipo", "Tipo")
                        .WithMany("Questoes")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nivel");

                    b.Navigation("Tema");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Quiz", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.UsuarioConquista", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Conquista", "Conquista")
                        .WithMany("UsuarioConquistas")
                        .HasForeignKey("ConquistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.Usuario", "Usuario")
                        .WithMany("UsuarioConquistas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conquista");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.UsuarioResposta", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Questao", "Questao")
                        .WithMany("QuestoesRespondidas")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.Quiz", "Quiz")
                        .WithMany("QuestoesRespondidas")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.Usuario", "Usuario")
                        .WithMany("QuestoesRespondidas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");

                    b.Navigation("Quiz");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.UsuarioStats", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Usuario", "Usuario")
                        .WithOne("Stats")
                        .HasForeignKey("SenacQuizApp.Modelos.UsuarioStats", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.UsuarioNivel", "Nivel")
                        .WithMany()
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nivel");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Conquista", b =>
                {
                    b.Navigation("UsuarioConquistas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Questao", b =>
                {
                    b.Navigation("Alternativas");

                    b.Navigation("QuestoesRespondidas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.QuestaoNivel", b =>
                {
                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.QuestaoTema", b =>
                {
                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.QuestaoTipo", b =>
                {
                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Quiz", b =>
                {
                    b.Navigation("QuestoesRespondidas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuario", b =>
                {
                    b.Navigation("QuestoesRespondidas");

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("UsuarioConquistas");
                });
#pragma warning restore 612, 618
        }
    }
}
