// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SenacQuizApp.banco.config;

#nullable disable

namespace SenacQuizApp.Migrations
{
    [DbContext(typeof(AppContexto))]
    [Migration("20260814233442_AtualizaTabelas")]
    partial class AtualizaTabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PerguntaQuiz", b =>
                {
                    b.Property<int>("PerguntasId")
                        .HasColumnType("integer");

                    b.Property<int>("QuizzesId")
                        .HasColumnType("integer");

                    b.HasKey("PerguntasId", "QuizzesId");

                    b.HasIndex("QuizzesId");

                    b.ToTable("PerguntaQuiz");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Conquista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Conquistas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.NivelPergunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("NiveisPerguntas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.NivelUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PontosMax")
                        .HasColumnType("integer");

                    b.Property<int>("PontosMin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("NiveisUsuarios");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Pergunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("NivelId")
                        .HasColumnType("integer");

                    b.Property<int>("TemaId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NivelId");

                    b.HasIndex("TemaId");

                    b.ToTable("Perguntas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.PerguntaRespondida", b =>
                {
                    b.Property<int>("QuizTentativaId")
                        .HasColumnType("integer");

                    b.Property<int>("PerguntaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Acertou")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataDeResposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("integer");

                    b.Property<int>("QuizTentativaQuizId")
                        .HasColumnType("integer");

                    b.Property<int>("QuizTentativaUsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("QuizTentativaId", "PerguntaId");

                    b.HasIndex("PerguntaId");

                    b.HasIndex("QuizTentativaUsuarioId", "QuizTentativaQuizId");

                    b.ToTable("PerguntasRespondidas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataDeCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("QuantidadePerguntas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.HasKey("Id");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.QuizTentativa", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("PontuacaoFinal")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "QuizId");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizzesTentativas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.TemaPergunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("TemasPerguntas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxAcertosConsecutivos")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("NivelUsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("PontuacaoTotal")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalAcertos")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRespondidos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.HasIndex("NivelUsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.UsuarioConquista", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("ConquistaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataDeAquisicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "ConquistaId");

                    b.HasIndex("ConquistaId");

                    b.ToTable("UsuarioConquistas");
                });

            modelBuilder.Entity("PerguntaQuiz", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Pergunta", null)
                        .WithMany()
                        .HasForeignKey("PerguntasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.Quiz", null)
                        .WithMany()
                        .HasForeignKey("QuizzesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Pergunta", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.NivelPergunta", "Nivel")
                        .WithMany()
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.TemaPergunta", "Tema")
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("SenacQuizApp.Modelos.OpcaoResposta", "Respostas", b1 =>
                        {
                            b1.Property<int>("PerguntaId")
                                .HasColumnType("integer");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<bool>("IsCorreta")
                                .HasColumnType("boolean");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PerguntaId", "__synthesizedOrdinal");

                            b1.ToTable("Perguntas");

                            b1
                                .ToJson("Respostas")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PerguntaId");
                        });

                    b.Navigation("Nivel");

                    b.Navigation("Respostas");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.PerguntaRespondida", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Pergunta", "Pergunta")
                        .WithMany("PerguntasRespondidas")
                        .HasForeignKey("PerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.QuizTentativa", "QuizTentativa")
                        .WithMany("PerguntasRespondidas")
                        .HasForeignKey("QuizTentativaUsuarioId", "QuizTentativaQuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pergunta");

                    b.Navigation("QuizTentativa");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.QuizTentativa", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Quiz", "Quiz")
                        .WithMany("QuizTentativas")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.Usuario", "Usuario")
                        .WithMany("QuizTentativas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuario", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.NivelUsuario", "Nivel")
                        .WithMany()
                        .HasForeignKey("NivelUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.UsuarioConquista", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Conquista", "Conquista")
                        .WithMany("UsuarioConquistas")
                        .HasForeignKey("ConquistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.Usuario", "Usuario")
                        .WithMany("UsuarioConquistas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conquista");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Conquista", b =>
                {
                    b.Navigation("UsuarioConquistas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Pergunta", b =>
                {
                    b.Navigation("PerguntasRespondidas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Quiz", b =>
                {
                    b.Navigation("QuizTentativas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.QuizTentativa", b =>
                {
                    b.Navigation("PerguntasRespondidas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuario", b =>
                {
                    b.Navigation("QuizTentativas");

                    b.Navigation("UsuarioConquistas");
                });
#pragma warning restore 612, 618
        }
    }
}
