// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SenacQuizApp.Data;

#nullable disable

namespace SenacQuizApp.Migrations
{
    [DbContext(typeof(QuizAppContexto))]
    [Migration("20260822050657_AtualizaTabelaUsuarioStats")]
    partial class AtualizaTabelaUsuarioStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PerguntaQuiz", b =>
                {
                    b.Property<int>("PerguntasId")
                        .HasColumnType("integer");

                    b.Property<int>("QuizzesId")
                        .HasColumnType("integer");

                    b.HasKey("PerguntasId", "QuizzesId");

                    b.HasIndex("QuizzesId");

                    b.ToTable("QuizPerguntas", (string)null);
                });

            modelBuilder.Entity("SenacQuizApp.Enums.PerguntaTema", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("PerguntaTemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Hardware"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Programação"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Redes"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Segurança Digital"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Sistemas Operacionais"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Ferramentas de Produtividade"
                        });
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Alternativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorreta")
                        .HasColumnType("boolean");

                    b.Property<int>("PerguntaId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PerguntaId");

                    b.ToTable("Alternativas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Conquista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Conquistas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Pergunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TemaId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TemaId");

                    b.ToTable("Perguntas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataConcluido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataExibido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<DateTime>("DataInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsConcluido")
                        .HasColumnType("boolean");

                    b.Property<int>("PontuacaoTotal")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("TempoDeConclusao")
                        .HasColumnType("interval");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "DataExibido")
                        .IsUnique();

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataDeCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataDeNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.UsuarioConquista", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("ConquistaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataDeAquisicao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UsuarioId", "ConquistaId");

                    b.HasIndex("ConquistaId");

                    b.ToTable("UsuarioConquistas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.UsuarioResposta", b =>
                {
                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.Property<int>("PerguntaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Acertou")
                        .HasColumnType("boolean");

                    b.Property<int>("Bonus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataDeResposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("PontuacaoFinal")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("QuizId", "PerguntaId");

                    b.HasIndex("PerguntaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuariosRespostas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.UsuarioStats", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("AtualAcertosConsecutivos")
                        .HasColumnType("integer");

                    b.Property<int>("MaxAcertosConsecutivos")
                        .HasColumnType("integer");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PontuacaoTotal")
                        .HasColumnType("integer");

                    b.Property<int?>("TemaMaisAcertadoId")
                        .HasColumnType("integer");

                    b.Property<int>("TemaTotalAcertos")
                        .HasColumnType("integer");

                    b.Property<int>("TemaTotalRespostas")
                        .HasColumnType("integer");

                    b.Property<int>("TotalAcertos")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRespondidos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TemaMaisAcertadoId");

                    b.ToTable("UsuariosStatus");
                });

            modelBuilder.Entity("PerguntaQuiz", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Pergunta", null)
                        .WithMany()
                        .HasForeignKey("PerguntasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.Quiz", null)
                        .WithMany()
                        .HasForeignKey("QuizzesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Alternativa", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Pergunta", "Pergunta")
                        .WithMany("Alternativas")
                        .HasForeignKey("PerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pergunta");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Pergunta", b =>
                {
                    b.HasOne("SenacQuizApp.Enums.PerguntaTema", "Tema")
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Quiz", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.UsuarioConquista", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Conquista", "Conquista")
                        .WithMany("UsuarioConquistas")
                        .HasForeignKey("ConquistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.Usuario", "Usuario")
                        .WithMany("UsuarioConquistas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conquista");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.UsuarioResposta", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Pergunta", "Pergunta")
                        .WithMany("PerguntasRespondidas")
                        .HasForeignKey("PerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.Quiz", "Quiz")
                        .WithMany("PerguntasRespondidas")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Modelos.Usuario", null)
                        .WithMany("UsuarioRespostas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Pergunta");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.UsuarioStats", b =>
                {
                    b.HasOne("SenacQuizApp.Modelos.Usuario", "Usuario")
                        .WithOne("Stats")
                        .HasForeignKey("SenacQuizApp.Modelos.UsuarioStats", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Enums.PerguntaTema", "TemaMaisAcertado")
                        .WithMany()
                        .HasForeignKey("TemaMaisAcertadoId");

                    b.Navigation("TemaMaisAcertado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Conquista", b =>
                {
                    b.Navigation("UsuarioConquistas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Pergunta", b =>
                {
                    b.Navigation("Alternativas");

                    b.Navigation("PerguntasRespondidas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Quiz", b =>
                {
                    b.Navigation("PerguntasRespondidas");
                });

            modelBuilder.Entity("SenacQuizApp.Modelos.Usuario", b =>
                {
                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("UsuarioConquistas");

                    b.Navigation("UsuarioRespostas");
                });
#pragma warning restore 612, 618
        }
    }
}
