// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SenacQuizApp.banco.config;

#nullable disable

namespace SenacQuizApp.Migrations
{
    [DbContext(typeof(AppContexto))]
    [Migration("20260814004718_AdicionaTabelasNovas")]
    partial class AdicionaTabelasNovas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SenacQuizApp.Entidades.NivelPergunta", b =>
                {
                    b.Property<int>("NivelPerguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NivelPerguntaId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer");

                    b.HasKey("NivelPerguntaId");

                    b.ToTable("NivelPergunta");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.NivelUsuario", b =>
                {
                    b.Property<int>("NivelUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NivelUsuarioId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PontosMax")
                        .HasColumnType("integer");

                    b.Property<int>("PontosMin")
                        .HasColumnType("integer");

                    b.HasKey("NivelUsuarioId");

                    b.ToTable("NivelUsuario");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Pergunta", b =>
                {
                    b.Property<int>("PerguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PerguntaId"));

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NivelPerguntaId")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("Respostas")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("TemaPerguntaId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PerguntaId");

                    b.HasIndex("NivelPerguntaId");

                    b.HasIndex("TemaPerguntaId");

                    b.ToTable("Perguntas");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.TemaPergunta", b =>
                {
                    b.Property<int>("TemaPerguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TemaPerguntaId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TemaPerguntaId");

                    b.ToTable("TemaPergunta");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxAcertosConsecutivos")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("NivelUsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("PontuacaoTotal")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalAcertos")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRespondidos")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.HasIndex("NivelUsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Pergunta", b =>
                {
                    b.HasOne("SenacQuizApp.Entidades.NivelPergunta", "Nivel")
                        .WithMany()
                        .HasForeignKey("NivelPerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenacQuizApp.Entidades.TemaPergunta", "Tema")
                        .WithMany()
                        .HasForeignKey("TemaPerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nivel");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("SenacQuizApp.Entidades.Usuario", b =>
                {
                    b.HasOne("SenacQuizApp.Entidades.NivelUsuario", "Nivel")
                        .WithMany()
                        .HasForeignKey("NivelUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nivel");
                });
#pragma warning restore 612, 618
        }
    }
}
